[build]
  # Répertoire de build
  publish = "frontend/build"
  
  # Commande de build
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  # Version Node.js
  NODE_VERSION = "20"
  
  # Variables d'environnement par défaut
  REACT_APP_ENV = "production"
  CI = "false"

# Redirections pour React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.home21.example.com"

# Cache des assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache du service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Configuration des branches
[context.production]
  command = "cd frontend && npm ci && npm run build"

[context.deploy-preview]
  command = "cd frontend && npm ci && npm run build"

[context.branch-deploy]
  command = "cd frontend && npm ci && npm run build"

# Variables d'environnement par contexte
[context.production.environment]
  REACT_APP_API_URL = "https://api.home21.example.com"
  REACT_APP_ENV = "production"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://api-staging.home21.example.com"
  REACT_APP_ENV = "preview"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://api-dev.home21.example.com"
  REACT_APP_ENV = "development"

# Fonctions Netlify (si nécessaires)
[functions]
  directory = "netlify/functions"